/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.timemanagement.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the TMActivity service. Represents a row in the &quot;timemanagement_TMActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.timemanagement.model.impl.TMActivityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.timemanagement.model.impl.TMActivityImpl}.
 * </p>
 *
 * @author Istvan Sajtos, Zsolt Szabo
 * @see TMActivity
 * @see com.liferay.timemanagement.model.impl.TMActivityImpl
 * @see com.liferay.timemanagement.model.impl.TMActivityModelImpl
 * @generated
 */
public interface TMActivityModel extends AttachedModel, BaseModel<TMActivity>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a t m activity model instance should use the {@link TMActivity} interface instead.
	 */

	/**
	 * Returns the primary key of this t m activity.
	 *
	 * @return the primary key of this t m activity
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t m activity.
	 *
	 * @param primaryKey the primary key of this t m activity
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the activity ID of this t m activity.
	 *
	 * @return the activity ID of this t m activity
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this t m activity.
	 *
	 * @param activityId the activity ID of this t m activity
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the group ID of this t m activity.
	 *
	 * @return the group ID of this t m activity
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this t m activity.
	 *
	 * @param groupId the group ID of this t m activity
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this t m activity.
	 *
	 * @return the company ID of this t m activity
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this t m activity.
	 *
	 * @param companyId the company ID of this t m activity
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this t m activity.
	 *
	 * @return the user ID of this t m activity
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this t m activity.
	 *
	 * @param userId the user ID of this t m activity
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this t m activity.
	 *
	 * @return the user uuid of this t m activity
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t m activity.
	 *
	 * @param userUuid the user uuid of this t m activity
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this t m activity.
	 *
	 * @return the user name of this t m activity
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this t m activity.
	 *
	 * @param userName the user name of this t m activity
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this t m activity.
	 *
	 * @return the create date of this t m activity
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this t m activity.
	 *
	 * @param createDate the create date of this t m activity
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this t m activity.
	 *
	 * @return the modified date of this t m activity
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t m activity.
	 *
	 * @param modifiedDate the modified date of this t m activity
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the activity name of this t m activity.
	 *
	 * @return the activity name of this t m activity
	 */
	public String getActivityName();

	/**
	 * Returns the localized activity name of this t m activity in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized activity name of this t m activity
	 */
	@AutoEscape
	public String getActivityName(Locale locale);

	/**
	 * Returns the localized activity name of this t m activity in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized activity name of this t m activity. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getActivityName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized activity name of this t m activity in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized activity name of this t m activity
	 */
	@AutoEscape
	public String getActivityName(String languageId);

	/**
	 * Returns the localized activity name of this t m activity in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized activity name of this t m activity
	 */
	@AutoEscape
	public String getActivityName(String languageId, boolean useDefault);

	@AutoEscape
	public String getActivityNameCurrentLanguageId();

	@AutoEscape
	public String getActivityNameCurrentValue();

	/**
	 * Returns a map of the locales and localized activity names of this t m activity.
	 *
	 * @return the locales and localized activity names of this t m activity
	 */
	public Map<Locale, String> getActivityNameMap();

	/**
	 * Sets the activity name of this t m activity.
	 *
	 * @param activityName the activity name of this t m activity
	 */
	public void setActivityName(String activityName);

	/**
	 * Sets the localized activity name of this t m activity in the language.
	 *
	 * @param activityName the localized activity name of this t m activity
	 * @param locale the locale of the language
	 */
	public void setActivityName(String activityName, Locale locale);

	/**
	 * Sets the localized activity name of this t m activity in the language, and sets the default locale.
	 *
	 * @param activityName the localized activity name of this t m activity
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setActivityName(String activityName, Locale locale,
		Locale defaultLocale);

	public void setActivityNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized activity names of this t m activity from the map of locales and localized activity names.
	 *
	 * @param activityNameMap the locales and localized activity names of this t m activity
	 */
	public void setActivityNameMap(Map<Locale, String> activityNameMap);

	/**
	 * Sets the localized activity names of this t m activity from the map of locales and localized activity names, and sets the default locale.
	 *
	 * @param activityNameMap the locales and localized activity names of this t m activity
	 * @param defaultLocale the default locale
	 */
	public void setActivityNameMap(Map<Locale, String> activityNameMap,
		Locale defaultLocale);

	/**
	 * Returns the fully qualified class name of this t m activity.
	 *
	 * @return the fully qualified class name of this t m activity
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this t m activity.
	 *
	 * @return the class name ID of this t m activity
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this t m activity.
	 *
	 * @param classNameId the class name ID of this t m activity
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this t m activity.
	 *
	 * @return the class p k of this t m activity
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this t m activity.
	 *
	 * @param classPK the class p k of this t m activity
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the class uuid of this t m activity.
	 *
	 * @return the class uuid of this t m activity
	 */
	@AutoEscape
	public String getClassUuid();

	/**
	 * Sets the class uuid of this t m activity.
	 *
	 * @param classUuid the class uuid of this t m activity
	 */
	public void setClassUuid(String classUuid);

	/**
	 * Returns the description of this t m activity.
	 *
	 * @return the description of this t m activity
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this t m activity in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this t m activity
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this t m activity in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this t m activity. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this t m activity in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this t m activity
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this t m activity in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this t m activity
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this t m activity.
	 *
	 * @return the locales and localized descriptions of this t m activity
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this t m activity.
	 *
	 * @param description the description of this t m activity
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this t m activity in the language.
	 *
	 * @param description the localized description of this t m activity
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this t m activity in the language, and sets the default locale.
	 *
	 * @param description the localized description of this t m activity
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this t m activity from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this t m activity
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this t m activity from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this t m activity
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the end date of this t m activity.
	 *
	 * @return the end date of this t m activity
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this t m activity.
	 *
	 * @param endDate the end date of this t m activity
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the priority of this t m activity.
	 *
	 * @return the priority of this t m activity
	 */
	public int getPriority();

	/**
	 * Sets the priority of this t m activity.
	 *
	 * @param priority the priority of this t m activity
	 */
	public void setPriority(int priority);

	/**
	 * Returns the reminder date of this t m activity.
	 *
	 * @return the reminder date of this t m activity
	 */
	public Date getReminderDate();

	/**
	 * Sets the reminder date of this t m activity.
	 *
	 * @param reminderDate the reminder date of this t m activity
	 */
	public void setReminderDate(Date reminderDate);

	/**
	 * Returns the scheduled date of this t m activity.
	 *
	 * @return the scheduled date of this t m activity
	 */
	public Date getScheduledDate();

	/**
	 * Sets the scheduled date of this t m activity.
	 *
	 * @param scheduledDate the scheduled date of this t m activity
	 */
	public void setScheduledDate(Date scheduledDate);

	/**
	 * Returns the start date of this t m activity.
	 *
	 * @return the start date of this t m activity
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this t m activity.
	 *
	 * @param startDate the start date of this t m activity
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the visible of this t m activity.
	 *
	 * @return the visible of this t m activity
	 */
	public boolean getVisible();

	/**
	 * Returns <code>true</code> if this t m activity is visible.
	 *
	 * @return <code>true</code> if this t m activity is visible; <code>false</code> otherwise
	 */
	public boolean isVisible();

	/**
	 * Sets whether this t m activity is visible.
	 *
	 * @param visible the visible of this t m activity
	 */
	public void setVisible(boolean visible);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public String[] getAvailableLanguageIds();

	public String getDefaultLanguageId();

	public void prepareLocalizedFieldsForImport() throws LocaleException;

	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(TMActivity tmActivity);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TMActivity> toCacheModel();

	@Override
	public TMActivity toEscapedModel();

	@Override
	public TMActivity toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}